namespace IntegraCVP.Application.Dtos;

public class DadoArquivoTextoDto
{
    public string PRODUTO { get; set; }
    public string COD_PROD { get; set; }
    public string PROC_SUSEP { get; set; }
    public string NOME_CLIENTE { get; set; }
    public string CPF { get; set; }
    public string DT_NASC { get; set; }
    public string PARCELA { get; set; }
    public string NUMCDBARRA { get; set; }
    public string DTVENCTO { get; set; }
    public string NCEDENTE { get; set; }
    public string CEDENTE { get; set; }
    public string DTDOCTO { get; set; }
    public string NUMDOCTO { get; set; }
    public string DTPROCESS { get; set; }
    public string NSNUMERO { get; set; }
    public string VALDOCTO { get; set; }
    public string MENSA1 { get; set; }
    public string MENSA2 { get; set; }
    public string MENSA3 { get; set; }
    public string MENSA4 { get; set; }
    public string MENSA5 { get; set; }
    public string MENSA6 { get; set; }
    public string MENSA7 { get; set; }
    public string VALCOBRADO { get; set; }
    public string CODBARRA { get; set; }
    public string SACADOR { get; set; }
    public string END_SAC { get; set; }
    public string CEP_SAC { get; set; }
    public string CGCCPFSUB { get; set; }
    public string DTPOSTAGEM { get; set; }
    public string NUMOBJETO { get; set; }
    public string DESTINATARIO { get; set; }
    public string ENDERECO { get; set; }
    public string BAIRRO { get; set; }
    public string CIDADE { get; set; }
    public string UF { get; set; }
    public string CEP { get; set; }
    public string REMETENTE { get; set; }
    public string REMET_ENDERECO { get; set; }
    public string REMET_BAIRRO { get; set; }
    public string REMET_CIDADE { get; set; }
    public string REMET_UF { get; set; }
    public string REMET_CEP { get; set; }
    public string PARCELA1 { get; set; }
    public string PARCELA2 { get; set; }
    public string PARCELA3 { get; set; }
    public string PARCELA4 { get; set; }
    public string PARCELA5 { get; set; }
    public string TEXTO01 { get; set; }
    public string TEXTO02 { get; set; }
    public string TEXTO03 { get; set; }
    public string TEXTO11 { get; set; }
    public string TEXTO12 { get; set; }
    public string TEXTO13 { get; set; }
    public string TEXTO14 { get; set; }
    public string TEXTO15 { get; set; }
    public string TEXTO21 { get; set; }
    public string TEXTO22 { get; set; }
    public string TEXTO23 { get; set; }
    public string TEXTO24 { get; set; }
    public string TEXTO25 { get; set; }
    public string TEXTO31 { get; set; }
    public string TEXTO32 { get; set; }
    public string TEXTO33 { get; set; }
    public string TEXTO34 { get; set; }
    public string TEXTO35 { get; set; }
    public string TEXTO41 { get; set; }
    public string TEXTO42 { get; set; }
    public string TEXTO43 { get; set; }
    public string TEXTO44 { get; set; }
    public string TEXTO45 { get; set; }
    public string TEXTO51 { get; set; }
    public string TEXTO52 { get; set; }
    public string TEXTO53 { get; set; }
    public string TEXTO54 { get; set; }
    public string TEXTO55 { get; set; }
    public string TEXTO91 { get; set; }
    public string TEXTO92 { get; set; }
    public string TEXTO93 { get; set; }
    public string TEXTO94 { get; set; }
    public string TEXTO95 { get; set; }
    public string VALOR { get; set; }
    public string VALOR1 { get; set; }
    public string VL_MORTE { get; set; }
    public string VL_ACID { get; set; }
    public string VL_INVAL { get; set; }
    public string VL_CUSTO { get; set; }
    public string CODIGO_CIF { get; set; }
    public string POSTNET { get; set; }
    public string NUM_CERTIFICADO { get; set; }
    public string LINHACOMPLETA { get; set; }
    public string FORM { get; set; }
}
